version: "2"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka
    # volumes:
    # mysql-data:
    #     driver: local

  db_admin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
      - db:db
    ports:
      - "8081:80"

  omeka-s:
    image: sunny3p/omeka-classic:latest
    # links:
    # - mysql
    restart: always
    volumes:
      - ./app:/var/www/html/files
    ports:
      - 8080:80
